# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dreamec.github.io
title: Dreamec
email: dreamecDpii@gmail.com
description: > # "Somos una empresa joven dedicada al sector de los Sistemas Inteligentes en web.
    Trabajamos con sistemas de minería de datos, sistemas expertos y servicios de implantación de éstos en
    webs."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Contacto
    url: mailTo:dreamecDpii@gmail.com
    icon: envelope
  - title: Twitter
    url: https://twitter.com/DreamecES
    icon: twitter
  - title: Productos
    url: "#product"
    icon: th-large
  - title: Servicios
    url: "#services"
    icon: cloud